name: airtrafficsim
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  - numpy
  - pandas
  - Flask
  - Flask-SocketIO
  - Eventlet
  - cartopy
  - cdsapi
  - xarray
  - openap
  - pydata-sphinx-theme
  # - pip
  # - pip:
  #   - -r requirements.txt
